name: Config translation example module
description: Example module with translatable admin form
package: Custom
core_version_requirement: ^8 || ^9
type: module
core: 8.x
dependencies:
  - drupal:locale
  - config_translation
