patchinfo.settings:
  type: config_object
  label: 'Patchinfo settings'
  mapping:
    exclude from update check:
      type: sequence
      label: 'Exclude from update check'
      sequence:
        type: string
